"""Action-dependency persistence port."""
from typing import Protocol

class ActionDependencyRepository(Protocol):
    def add(self, *, action_id: str, depends_on_action_id: str) -> None: ...
    def list_dependencies(self, action_id: str) -> tuple[str, ...]: ...
    def list_dependents(self, action_id: str) -> tuple[str, ...]: ...
