"""Action persistence port."""
from typing import Protocol
from google_work_agent.domain import ActionCommand, ActionStatus, CommandResult
from google_work_agent.ports.models import ActionRecord

class ActionRepository(Protocol):
    def get_by_id(self, action_id: str) -> ActionRecord | None: ...
    def insert_read_action(self, action: ActionRecord) -> None: ...
    def insert_write_action(self, action: ActionRecord) -> None: ...
    def claim_read(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def complete_read(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def finalize_read(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def fail_read(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def approve_write(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def reject_write(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def modify_write(self, action_id: str, *, expected_version: int, updated_at_ms: int, arguments_json: str, arguments_hash: str, risk: dict[str, object]) -> CommandResult[ActionStatus, ActionCommand]: ...
    def update_risk_snapshot(self, action_id: str, *, expected_version: int, updated_at_ms: int, risk: dict[str, object]) -> None: ...
    def claim_execution(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def store_success(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def mark_failed(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def mark_unknown_result(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def recover_existing_result(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def resolve_unknown_as_failed(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def prepare_write_retry(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def cancel_pending(self, action_id: str, *, expected_version: int, updated_at_ms: int) -> CommandResult[ActionStatus, ActionCommand]: ...
    def store_verification(self, action_id: str, *, expected_version: int, updated_at_ms: int, verification_status: str) -> CommandResult[ActionStatus, ActionCommand]: ...
    def mark_dependency_blocked(self, action_id: str, *, updated_at_ms: int) -> bool: ...
    def list_by_plan(self, plan_id: str) -> tuple[ActionRecord, ...]: ...
    def list_ready_actions(self, plan_id: str) -> tuple[ActionRecord, ...]: ...
    def connector_id_for_action(self, action_id: str) -> str: ...
