"""Approval persistence port."""
from typing import Protocol
from google_work_agent.ports.models import ApprovalRecord

class ApprovalRepository(Protocol):
    def get_by_id(self, approval_id: str) -> ApprovalRecord | None: ...
    def get_active_by_action(self, action_id: str) -> ApprovalRecord | None: ...
    def insert(self, record: ApprovalRecord) -> None: ...
    def mark_consumed(self, approval_id: str, *, consumed_at_ms: int) -> None: ...
    def revoke_active_by_action(self, action_id: str) -> tuple[str, ...]: ...
    def list_by_action(self, action_id: str) -> tuple[ApprovalRecord, ...]: ...
