"""Audit-event persistence port."""
from typing import Protocol
from google_work_agent.ports.models import AuditEventRecord, PersistedAuditEventRecord

class AuditRepository(Protocol):
    def append(self, event: AuditEventRecord) -> None: ...
    def add(self, event: AuditEventRecord) -> None: ...
    def list_by_aggregate(self, *, run_id: str | None, action_id: str | None = None, cursor_after: int | None = None, limit: int = 100) -> tuple[PersistedAuditEventRecord, ...]: ...
    def list_after_cursor(self, *, cursor_after: int | None, limit: int = 100) -> tuple[PersistedAuditEventRecord, ...]: ...
    def list_before_retention_cutoff(self, *, cutoff_ms: int, limit: int) -> tuple[PersistedAuditEventRecord, ...]: ...
    def purge_before_cutoff(self, *, cutoff_ms: int, limit: int) -> int: ...
