"""Conversation persistence port."""
from typing import Protocol
from google_work_agent.ports.models import ConversationRecord

class ConversationRepository(Protocol):
    def get_by_id(self, conversation_id: str) -> ConversationRecord | None: ...
    def add(self, conversation: ConversationRecord) -> None: ...
    def touch(self, conversation_id: str, *, updated_at_ms: int) -> None: ...
