"""Evidence persistence port."""
from typing import Protocol
from google_work_agent.ports.models import EvidenceRecord

class EvidenceRepository(Protocol):
    def insert(self, record: EvidenceRecord) -> None: ...
    def link_to_action(self, *, action_id: str, evidence_id: str) -> None: ...
    def list_by_action(self, action_id: str) -> tuple[EvidenceRecord, ...]: ...
