"""Execution-attempt persistence port."""
from typing import Protocol
from google_work_agent.domain import ExecutionAttemptStatus
from google_work_agent.ports.models import ExecutionAttemptRecord

class ExecutionAttemptRepository(Protocol):
    def get_by_id(self, attempt_id: str) -> ExecutionAttemptRecord | None: ...
    def get_active_by_approval(self, approval_id: str) -> ExecutionAttemptRecord | None: ...
    def insert_claimed(self, record: ExecutionAttemptRecord) -> None: ...
    def mark_succeeded(self, attempt_id: str, *, expected_version: int, result_resource_ref_id: str | None, response_metadata_json: str | None, finished_at_ms: int) -> ExecutionAttemptRecord: ...
    def mark_failed(self, attempt_id: str, *, expected_version: int, error_code: str, error_detail_json: str, finished_at_ms: int) -> ExecutionAttemptRecord: ...
    def mark_unknown_result(self, attempt_id: str, *, expected_version: int, error_code: str, error_detail_json: str, finished_at_ms: int) -> ExecutionAttemptRecord: ...
    def update_status(self, attempt_id: str, *, expected_version: int, status: ExecutionAttemptStatus, error_code: str | None, error_detail_json: str | None, result_resource_ref_id: str | None, response_metadata_json: str | None, finished_at_ms: int | None) -> ExecutionAttemptRecord: ...
    def list_by_approval(self, approval_id: str) -> tuple[ExecutionAttemptRecord, ...]: ...
