"""Plan persistence port."""
from typing import Protocol
from google_work_agent.ports.models import PlanRecord

class PlanRepository(Protocol):
    def get_by_id(self, plan_id: str) -> PlanRecord | None: ...
    def insert_draft(self, plan: PlanRecord) -> None: ...
    def require_review(self, plan_id: str) -> int: ...
    def store_review_result(self, plan_id: str, *, expected_review_version: int, review_status: str) -> bool: ...
    def activate(self, plan_id: str) -> None: ...
    def wait_for_approval(self, plan_id: str) -> None: ...
    def activate_waiting(self, plan_id: str) -> None: ...
    def complete(self, plan_id: str) -> None: ...
    def cancel(self, plan_id: str) -> None: ...
    def supersede(self, plan_id: str) -> None: ...
    def list_by_run(self, run_id: str) -> tuple[PlanRecord, ...]: ...
