"""Resource-reference persistence port."""
from typing import Protocol
from google_work_agent.ports.models import ResourceRefRecord

class ResourceRefRepository(Protocol):
    def get_by_id(self, resource_ref_id: str) -> ResourceRefRecord | None: ...
    def get_by_unique_key(self, *, run_id: str, connector_id: str, resource_type: str, resource_id: str) -> ResourceRefRecord | None: ...
    def upsert(self, record: ResourceRefRecord) -> None: ...
    def list_by_run(self, run_id: str) -> tuple[ResourceRefRecord, ...]: ...
    def connector_id_for_resource_ref(self, resource_ref_id: str) -> str: ...
