"""Run persistence port."""

from typing import Protocol

from google_work_agent.domain import CommandResult, RunCommand, RunStatus
from google_work_agent.ports.models import RunCreateRecord, RunRecord


class RunRepository(Protocol):
    def get_by_id(self, run_id: str) -> RunRecord | None: ...
    def get_open_by_conversation(self, conversation_id: str) -> RunRecord | None: ...
    def add(self, run: RunCreateRecord) -> None: ...
    def start_analysis(self, run_id: str, *, expected_version: int, finished_at_ms: int | None = None) -> CommandResult[RunStatus, RunCommand]: ...
    def begin_retrieval(self, run_id: str, *, expected_version: int, finished_at_ms: int | None = None) -> CommandResult[RunStatus, RunCommand]: ...
    def begin_planning(self, run_id: str, *, expected_version: int, finished_at_ms: int | None = None) -> CommandResult[RunStatus, RunCommand]: ...
    def replan(self, run_id: str, *, expected_version: int, finished_at_ms: int | None = None) -> CommandResult[RunStatus, RunCommand]: ...
    def request_confirmation(self, run_id: str, *, expected_version: int, finished_at_ms: int | None = None) -> CommandResult[RunStatus, RunCommand]: ...
    def resume_confirmation(self, run_id: str, *, expected_version: int, resume_status: RunStatus, finished_at_ms: int | None = None) -> CommandResult[RunStatus, RunCommand]: ...
    def resume_after_reauth(self, run_id: str, *, expected_version: int, resume_status: RunStatus, finished_at_ms: int | None = None) -> CommandResult[RunStatus, RunCommand]: ...
    def complete_answer_only_run(self, run_id: str, *, expected_version: int, finished_at_ms: int) -> CommandResult[RunStatus, RunCommand]: ...
    def complete_write_run(self, run_id: str, *, expected_version: int, finished_at_ms: int) -> CommandResult[RunStatus, RunCommand]: ...
    def finalize_action_outcomes(self, run_id: str, *, expected_version: int, finished_at_ms: int) -> CommandResult[RunStatus, RunCommand]: ...
    def block_run(self, run_id: str, *, expected_version: int, finished_at_ms: int) -> CommandResult[RunStatus, RunCommand]: ...
    def fail_run(self, run_id: str, *, expected_version: int, finished_at_ms: int) -> CommandResult[RunStatus, RunCommand]: ...
    def publish_read_only_plan(self, run_id: str, *, expected_version: int, finished_at_ms: int | None = None) -> CommandResult[RunStatus, RunCommand]: ...
    def complete_read_only_run(self, run_id: str, *, expected_version: int, finished_at_ms: int) -> CommandResult[RunStatus, RunCommand]: ...
    def publish_write_plan(self, run_id: str, *, expected_version: int, finished_at_ms: int | None = None) -> CommandResult[RunStatus, RunCommand]: ...
    def request_cancel(self, run_id: str, *, expected_version: int) -> CommandResult[RunStatus, RunCommand]: ...
    def finalize_cancel(self, run_id: str, *, expected_version: int, finished_at_ms: int) -> CommandResult[RunStatus, RunCommand]: ...
    def require_reauth(self, run_id: str, *, expected_version: int, finished_at_ms: int | None = None) -> CommandResult[RunStatus, RunCommand]: ...
    def require_recovery(self, run_id: str, *, expected_version: int, finished_at_ms: int | None = None) -> CommandResult[RunStatus, RunCommand]: ...
    def resolve_recovery(self, run_id: str, *, expected_version: int, recovery_next_status: RunStatus, finished_at_ms: int | None = None) -> CommandResult[RunStatus, RunCommand]: ...
    def set_recovery_required(self, run_id: str, *, finished_at_ms: int | None = None) -> RunRecord: ...
    def set_reauth_required(self, run_id: str, *, finished_at_ms: int | None = None) -> RunRecord: ...
    def set_verifying(self, run_id: str, *, finished_at_ms: int | None = None) -> RunRecord: ...
