"""Trace-event persistence port."""
from typing import Protocol
from google_work_agent.ports.models import PersistedTraceEventRecord, TraceEventRecord

class TraceRepository(Protocol):
    def append(self, event: TraceEventRecord) -> None: ...
    def add(self, event: TraceEventRecord) -> None: ...
    def list_by_run_after_cursor(self, *, run_id: str, cursor_after: int | None, limit: int = 100) -> tuple[PersistedTraceEventRecord, ...]: ...
    def list_before_retention_cutoff(self, *, cutoff_ms: int, limit: int) -> tuple[PersistedTraceEventRecord, ...]: ...
    def purge_before_cutoff(self, *, cutoff_ms: int, limit: int) -> int: ...
