"""Action lifecycle domain primitives."""

from enum import StrEnum


class ActionCommand(StrEnum):
    """Action lifecycle transition commands."""

    APPROVE_ACTION = "APPROVE_ACTION"
    MODIFY_ACTION = "MODIFY_ACTION"
    REJECT_ACTION = "REJECT_ACTION"
    EXPIRE_APPROVAL = "EXPIRE_APPROVAL"
    CLAIM_READ_ACTION = "CLAIM_READ_ACTION"
    COMPLETE_READ_ACTION = "COMPLETE_READ_ACTION"
    FINALIZE_READ_ACTION = "FINALIZE_READ_ACTION"
    FAIL_READ_ACTION = "FAIL_READ_ACTION"
    CLAIM_EXECUTION = "CLAIM_EXECUTION"
    STORE_SUCCESS = "STORE_SUCCESS"
    MARK_FAILED = "MARK_FAILED"
    MARK_UNKNOWN_RESULT = "MARK_UNKNOWN_RESULT"
    RECOVER_EXISTING_RESULT = "RECOVER_EXISTING_RESULT"
    RESOLVE_AS_FAILED = "RESOLVE_AS_FAILED"
    STORE_VERIFICATION = "STORE_VERIFICATION"
    PREPARE_WRITE_RETRY = "PREPARE_WRITE_RETRY"
    CANCEL_PENDING_ACTION = "CANCEL_PENDING_ACTION"
