"""Domain and policy core package."""

from google_work_agent.domain.action_risk import (
    MAX_ACTION_RISK_JSON_BYTES,
    canonicalize_action_risk,
    normalize_action_risk,
    parse_action_risk_json,
)
from google_work_agent.domain.calendar_conflict import (
    CalendarConflictDecision,
    CalendarConflictFreshness,
    CalendarConflictResult,
    CalendarEventCandidate,
    CalendarInterval,
    CalendarIntervalKind,
    CalendarWorkHours,
    classify_calendar_event,
    evaluate_calendar_conflict,
    intervals_overlap,
)
from google_work_agent.domain.canonical import (
    calculate_canonical_json_hash,
    canonicalize_json_value,
)
from google_work_agent.domain.action.model import ActionCommand
from google_work_agent.domain.run.model import RunCommand
from google_work_agent.domain.enums import (
    ActionStatus,
    ApprovalRequirement,
    ApprovalStatus,
    EffectType,
    ExecutionAttemptStatus,
    RecoveryPolicy,
    RecoveryResolution,
    ResultCode,
    RunStatus,
    VerificationPolicy,
    VerificationStatus,
)
from google_work_agent.domain.exceptions import (
    CommandHashMismatchError,
    DomainError,
    DuplicateCommandError,
    InvalidTransitionError,
    InvariantViolationError,
    PolicyViolationError,
    VersionConflictError,
)
from google_work_agent.domain.feasibility import (
    FeasibilityDecision,
    FeasibilityFreshness,
    FeasibilityResult,
    build_work_intervals,
    derive_deadline_cutoff,
    evaluate_feasibility,
    merge_intervals,
    subtract_intervals,
)
from google_work_agent.domain.policy import (
    ApprovalIntegrityInput,
    EvidencePolicyInput,
    validate_approval_integrity,
    validate_evidence_policy,
)
from google_work_agent.domain.results import CommandResult
from google_work_agent.domain.task_duplicate import (
    DuplicateDecision,
    DuplicateFreshness,
    TaskDuplicateCandidate,
    TaskDuplicateResult,
    evaluate_task_duplicate,
    normalize_scheduled_date,
    normalize_task_title,
)
from google_work_agent.domain.tool_registry import (
    DEFAULT_POLICY_VERSION,
    DEFAULT_TOOL_SCHEMA_VERSION,
    ConnectorToolCatalog,
    SignedToolRegistry,
    ToolRegistryEntry,
    build_p0_tool_registry,
)
from google_work_agent.domain.action.transitions.action import (
    next_allowed_action_commands,
    transition_action,
)
from google_work_agent.domain.run.transitions.run import (
    next_allowed_run_commands,
    transition_run,
)

__all__ = [
    "ActionCommand",
    "ActionStatus",
    "ApprovalIntegrityInput",
    "ApprovalRequirement",
    "ApprovalStatus",
    "CommandHashMismatchError",
    "CalendarConflictDecision",
    "CalendarConflictFreshness",
    "CalendarConflictResult",
    "CalendarEventCandidate",
    "CalendarInterval",
    "CalendarIntervalKind",
    "CalendarWorkHours",
    "CommandResult",
    "ConnectorToolCatalog",
    "DEFAULT_POLICY_VERSION",
    "DEFAULT_TOOL_SCHEMA_VERSION",
    "DomainError",
    "DuplicateDecision",
    "DuplicateFreshness",
    "DuplicateCommandError",
    "EvidencePolicyInput",
    "EffectType",
    "ExecutionAttemptStatus",
    "FeasibilityDecision",
    "FeasibilityFreshness",
    "FeasibilityResult",
    "InvalidTransitionError",
    "InvariantViolationError",
    "MAX_ACTION_RISK_JSON_BYTES",
    "PolicyViolationError",
    "RecoveryPolicy",
    "RecoveryResolution",
    "ResultCode",
    "RunCommand",
    "RunStatus",
    "SignedToolRegistry",
    "ToolRegistryEntry",
    "TaskDuplicateCandidate",
    "TaskDuplicateResult",
    "VerificationPolicy",
    "VerificationStatus",
    "VersionConflictError",
    "build_p0_tool_registry",
    "build_work_intervals",
    "calculate_canonical_json_hash",
    "canonicalize_action_risk",
    "canonicalize_json_value",
    "evaluate_task_duplicate",
    "evaluate_feasibility",
    "derive_deadline_cutoff",
    "evaluate_calendar_conflict",
    "classify_calendar_event",
    "intervals_overlap",
    "next_allowed_action_commands",
    "next_allowed_run_commands",
    "normalize_scheduled_date",
    "normalize_task_title",
    "merge_intervals",
    "normalize_action_risk",
    "parse_action_risk_json",
    "transition_action",
    "transition_run",
    "subtract_intervals",
    "validate_approval_integrity",
    "validate_evidence_policy",
]
