"""Domain command enum values."""

from enum import StrEnum


class RunCommand(StrEnum):
    """Run transition commands implemented without checkpoint context."""

    START_ANALYSIS = "START_ANALYSIS"
    BEGIN_RETRIEVAL = "BEGIN_RETRIEVAL"
    BEGIN_PLANNING = "BEGIN_PLANNING"
    BEGIN_VERIFICATION = "BEGIN_VERIFICATION"
    REQUEST_CONFIRMATION = "REQUEST_CONFIRMATION"
    BLOCK_RUN = "BLOCK_RUN"
    FAIL_RUN = "FAIL_RUN"
    PUBLISH_PLAN = "PUBLISH_PLAN"
    REPLAN = "REPLAN"
    COMPLETE_ANSWER_ONLY_RUN = "COMPLETE_ANSWER_ONLY_RUN"
    COMPLETE_WRITE_RUN = "COMPLETE_WRITE_RUN"
    FINALIZE_ACTION_OUTCOMES = "FINALIZE_ACTION_OUTCOMES"
    REQUEST_CANCEL = "REQUEST_CANCEL"
    FINALIZE_CANCEL = "FINALIZE_CANCEL"
    REQUIRE_REAUTH = "REQUIRE_REAUTH"
    REQUIRE_RECOVERY = "REQUIRE_RECOVERY"
    RESOLVE_RECOVERY = "RESOLVE_RECOVERY"


class ActionCommand(StrEnum):
    """Action transition commands implemented without persistence side effects."""

    APPROVE_ACTION = "APPROVE_ACTION"
    MODIFY_ACTION = "MODIFY_ACTION"
    REJECT_ACTION = "REJECT_ACTION"
    EXPIRE_APPROVAL = "EXPIRE_APPROVAL"
    CLAIM_READ_ACTION = "CLAIM_READ_ACTION"
    COMPLETE_READ_ACTION = "COMPLETE_READ_ACTION"
    FINALIZE_READ_ACTION = "FINALIZE_READ_ACTION"
    FAIL_READ_ACTION = "FAIL_READ_ACTION"
    CLAIM_EXECUTION = "CLAIM_EXECUTION"
    STORE_SUCCESS = "STORE_SUCCESS"
    MARK_FAILED = "MARK_FAILED"
    MARK_UNKNOWN_RESULT = "MARK_UNKNOWN_RESULT"
    RECOVER_EXISTING_RESULT = "RECOVER_EXISTING_RESULT"
    RESOLVE_AS_FAILED = "RESOLVE_AS_FAILED"
    STORE_VERIFICATION = "STORE_VERIFICATION"
    PREPARE_WRITE_RETRY = "PREPARE_WRITE_RETRY"
    CANCEL_PENDING_ACTION = "CANCEL_PENDING_ACTION"
